spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ecommerce
    username: hwang
    password: 1234

jpa:
  hibernate:
    ddl-auto: create
  properties:
    hibernate:
      format_sql : true

logging:
  lever:
    org.hibernate.SQL : debug
    org.hibernate.type : trace